group: travis_latest
language: python
cache: pip
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
install:
  # - pip install -r requirements.txt
  - pip install flake8 yapf
before_script:
  # stop the build if there are any unexpected flake8 issues
  - flake8 . --count --max-complexity=13 --show-source --statistics
  # exit-zero treats all errors as warnings.
  - flake8 . --count --exit-zero --max-complexity=10 --statistics
  # test to make sure the code is yapf compliant
  # TODO: Why is this not working as expected
  # - yapf --diff --recursive .
script:
  - true  # add other tests here
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
