model_params:
  fp16: false       # general flag
  model: SimpleNet  # model from NETWORKS to use

args:
  workers: 0
  expdir: "mnist_simple"
  logdir: "./logs/mnist_simple"

stages:

  state_params:
    main_metric: &reduce_metric precision01
    minimize_metric: False

  criterion_params:
      criterion: CrossEntropyLoss

  optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  stage1:
    args:
      epochs: &train_epoch 100
      batch_size: 64

    callbacks_params:
      loss:
        callback: LossCallback
      optimizer:
        callback: OptimizerCallback
      finder:
        callback: LRFinder
        final_lr: 0.1
        n_steps: 1000
      logger:
        callback: Logger
      tflogger:
        callback: TensorboardLogger
