model_params:
  model: SimpleNet

args:
  expdir: "mnist_simple"
  logdir: "./logs/mnist_simple"

stages:

  data_params:
    batch_size: 64
    n_workers: 0

  criterion_params:
      criterion: CrossEntropyLoss

  optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  stage1:
    state_params:
      n_epochs: &train_epoch 100

    callbacks_params:
      loss:
        callback: LossCallback
      optimizer:
        callback: OptimizerCallback
      finder:
        callback: LRFinder
        final_lr: 0.1
        n_steps: 1000
