model_params:
  model: SimpleNet

args:
  expdir: "_tests_mnist_stages"

stages:

  data_params:
    batch_size: 64
    num_workers: 0

  infer:

    callbacks_params:
      loader:
        callback: CheckpointCallback
      infer:
        callback: InferCallback
