model_params:
  model: SimpleNet


args:
  expdir: "cifar_stages"
  logdir: "./logs/cifar_stages"


stages:

  data_params:
    batch_size: 64
    n_workers: 1

  state_params:
    total_epochs: 2
    main_metric: &reduce_metric precision01
    minimize_metric: False

  criterion_params:
    criterion: CrossEntropyLoss

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [10]
    gamma: 0.3

  callbacks_params:
    loss:
      callback: LossCallback
    optimizer:
      callback: OptimizerCallback
    precision:
      callback: PrecisionCallback
      precision_args: [1, 3, 5]
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback

  stage1:

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

  # tune
  stage2:

    state_params:
      total_epochs: 3

    optimizer_params:
      optimizer: SGD
      lr: 0.0001
      weight_decay: 0.0001
